### PR TITLE
fix silly mistake in check-all-issues action

### PR DESCRIPTION
**Pull request by Irev-Dev**
related to kittycad/cio#37

### CODE REVIEW

**Comment by Irev-Dev** [comment]
I'll talk to you about this come your Monday @hanbollar, Think I need a special PAT for this one that has `['admin:org', 'repo', 'read:project']`, the `GLOBAL_PAT` that Jess added a while back doesn't have `read:project`.

**Comment by Irev-Dev** [comment]
Might as well give it full `project` permissions since there's only one subpoint to that anyway.
image

`['admin:org', 'repo', 'project']` is what I have for my test PAT for my test org, and it's working.

**Comment by Irev-Dev** [comment]
bump for the above @hanbollar

**Comment by hanbollar** [comment]
@Irev-Dev - just added a `GLOBAL_PROJECT_PAT` with those privileges : https://github.com/organizations/KittyCAD/settings/secrets/actions

**Comment by Irev-Dev** [comment]
Sorry @hanbollar, still having issues.
Issue now is the [token](https://github.com/KittyCAD/ts-actions/pull/151/files#diff-ca8e5c9aeddad3c8b22ccf8006d3607e969367d463d92335ead81e56426e2d8aR22) doesn't seem to exist for the action. I made the the action [throw if there's no token](https://github.com/KittyCAD/ts-actions/pull/151/files#diff-4d7d6beeeb22a18f77f8ed1943c7f70ae84de53fdaa73c44e6d974f11450023eR19) and sure enough that's what it's doing. I double checked typos and what not, and other env vars are coming through okay 🤷 

I can't access your last link because of permissions, so can't dig around myself to try and figure it out.

**Comment by Irev-Dev** [comment]
Sorry, I forgot to chase this up, wasn't able to get this working.

Could always touch base on this in our 1:1 to figure out what's going on with the token.

**Comment by hanbollar** [comment]
> Sorry, I forgot to chase this up, wasn't able to get this working.
> 
> Could always touch base on this in our 1:1 to figure out what's going on with the token.

no worries since this wasnt urgent

i'll start looking into this now to close out but will lyk if any questions ~

**Comment by hanbollar** [comment]
@Irev-Dev - looks like the actions ran - anything else needed here to get it going? or good to merge

**Comment by Irev-Dev** [comment]
Had a quick look at the action to try and get context on this again. Yeah looks good okay to me.

**Pull request merged**
